"""
This type stub file was generated by pyright.
"""

from ..xmlchemy import BaseOxmlElement

"""
lxml custom element classes for"""
class _BaseColorElement(BaseOxmlElement):
    """
    Base class for <a:srgbClr> """
    lumMod = ...
    lumOff = ...
    def add_lumMod(self, value):
        """
        Return a newly added <a"""
        ...
    
    def add_lumOff(self, value):
        """
        Return a newly added <a"""
        ...
    
    def clear_lum(self): # -> Self@_BaseColorElement:
        """
        Return self after remov"""
        ...
    


class CT_Color(BaseOxmlElement):
    """Custom element class for `a:fgCl"""
    eg_colorChoice = ...


class CT_HslColor(_BaseColorElement):
    """
    Custom element class for <a"""
    ...


class CT_Percentage(BaseOxmlElement):
    """
    Custom element class for <a"""
    val = ...


class CT_PresetColor(_BaseColorElement):
    """
    Custom element class for <a"""
    ...


class CT_SchemeColor(_BaseColorElement):
    """
    Custom element class for <a"""
    val = ...


class CT_ScRgbColor(_BaseColorElement):
    """
    Custom element class for <a"""
    ...


class CT_SRgbColor(_BaseColorElement):
    """
    Custom element class for <a"""
    val = ...


class CT_SystemColor(_BaseColorElement):
    """
    Custom element class for <a"""
    ...


