"""
This type stub file was generated by pyright.
"""

from pptx.oxml.xmlchemy import BaseOxmlElement

"""
lxml custom element classes for"""
class CT_Blip(BaseOxmlElement):
    """
    <a:blip> element
    """
    rEmbed = ...


class CT_BlipFillProperties(BaseOxmlElement):
    """
    Custom element class for <a"""
    _tag_seq = ...
    blip = ...
    srcRect = ...
    def crop(self, cropping): # -> None:
        """
        Set `a:srcRect` child t"""
        ...
    


class CT_GradientFillProperties(BaseOxmlElement):
    """`a:gradFill` custom element clas"""
    _tag_seq = ...
    gsLst = ...
    lin = ...
    path = ...
    @classmethod
    def new_gradFill(cls): # -> Any:
        """Return newly-created "loose" def"""
        ...
    


class CT_GradientStop(BaseOxmlElement):
    """`a:gs` custom element class."""
    eg_colorChoice = ...
    pos = ...


class CT_GradientStopList(BaseOxmlElement):
    """`a:gsLst` custom element class."""
    gs = ...
    @classmethod
    def new_gsLst(cls): # -> Any:
        """Return newly-created "loose" def"""
        ...
    


class CT_GroupFillProperties(BaseOxmlElement):
    """`a:grpFill` custom element class"""
    ...


class CT_LinearShadeProperties(BaseOxmlElement):
    """`a:lin` custom element class"""
    ang = ...


class CT_NoFillProperties(BaseOxmlElement):
    """`a:noFill` custom element class"""
    ...


class CT_PatternFillProperties(BaseOxmlElement):
    """`a:pattFill` custom element clas"""
    _tag_seq = ...
    fgClr = ...
    bgClr = ...
    prst = ...


class CT_RelativeRect(BaseOxmlElement):
    """`a:srcRect` element and perhaps """
    l = ...
    t = ...
    r = ...
    b = ...


class CT_SolidColorFillProperties(BaseOxmlElement):
    """`a:solidFill` custom element cla"""
    eg_colorChoice = ...


