"""
This type stub file was generated by pyright.
"""

from pptx.oxml.xmlchemy import BaseOxmlElement

"""lxml custom element classes for """
class CT_PresetLineDashProperties(BaseOxmlElement):
    """`a:prstDash` custom element clas"""
    val = ...


