"""
This type stub file was generated by pyright.
"""

from threading import Thread

__all__ = ["TMonitor", "TqdmSynchronisationWarning"]
class TqdmSynchronisationWarning(RuntimeWarning):
    """tqdm multi-thread/-process error"""
    ...


class TMonitor(Thread):
    """
    Monitoring thread for tqdm """
    _test = ...
    def __init__(self, tqdm_cls, sleep_interval) -> None:
        ...
    
    def exit(self): # -> bool:
        ...
    
    def get_instances(self): # -> list[Unknown]:
        ...
    
    def run(self): # -> None:
        ...
    
    def report(self): # -> bool:
        ...
    


