"""
This type stub file was generated by pyright.
"""

from .std import tqdm as std_tqdm

"""
Asynchronous progressbar decora"""
__author__ = ...
__all__ = ['tqdm_asyncio', 'tarange', 'tqdm', 'trange']
class tqdm_asyncio(std_tqdm):
    """
    Asynchronous-friendly versi"""
    def __init__(self, iterable=..., *args, **kwargs) -> None:
        ...
    
    def __aiter__(self): # -> Self@tqdm_asyncio:
        ...
    
    async def __anext__(self):
        ...
    
    def send(self, *args, **kwargs):
        ...
    
    @classmethod
    def as_completed(cls, fs, *, loop=..., timeout=..., total=..., **tqdm_kwargs): # -> Generator[Unknown, None, None]:
        """
        Wrapper for `asyncio.as"""
        ...
    
    @classmethod
    async def gather(cls, *fs, loop=..., timeout=..., total=..., **tqdm_kwargs): # -> list[Unknown]:
        """
        Wrapper for `asyncio.ga"""
        ...
    


def tarange(*args, **kwargs): # -> tqdm_asyncio:
    """
    A shortcut for `tqdm.asynci"""
    ...

tqdm = tqdm_asyncio
trange = ...
