"""
This type stub file was generated by pyright.
"""

import sys

"""
Enables multiple commonly used """
if sys.version_info[: 2] < (3, 6):
    tqdm = ...
    trange = ...
else:
    def trange(*args, **kwargs): # -> tqdm:
        """
        A shortcut for `tqdm.au"""
        ...
    
__all__ = ["tqdm", "trange"]
