"""
This type stub file was generated by pyright.
"""

"""
Module version for monitoring C"""
__all__ = ["main"]
log = ...
def cast(val, typ): # -> Any | bytes | bool:
    ...

def posix_pipe(fin, fout, delim=..., buf_size=..., callback=..., callback_len=...): # -> None:
    """
    Params
    ------
    fin  """
    ...

RE_OPTS = ...
RE_SHLEX = ...
UNSUPPORTED_OPTS = ...
CLI_EXTRA_DOC = ...
def main(fp=..., argv=...):
    """
    Parameters (internal use on"""
    ...

