"""
This type stub file was generated by pyright.
"""

from dask.callbacks import Callback

__author__ = ...
__all__ = ['TqdmCallback']
class TqdmCallback(Callback):
    """Dask callback for task progress."""
    def __init__(self, start=..., pretask=..., tqdm_class=..., **tqdm_kwargs) -> None:
        """
        Parameters
        ----"""
        ...
    
    def display(self): # -> None:
        """Displays in the current cell in """
        ...
    


