"""
This type stub file was generated by pyright.
"""

from .std import tqdm as std_tqdm

"""
Matplotlib GUI progressbar deco"""
__author__ = ...
__all__ = ['tqdm_gui', 'tgrange', 'tqdm', 'trange']
class tqdm_gui(std_tqdm):
    """Experimental Matplotlib GUI vers"""
    def __init__(self, *args, **kwargs) -> None:
        ...
    
    def close(self): # -> None:
        ...
    
    def clear(self, *_, **__): # -> None:
        ...
    
    def display(self, *_, **__):
        ...
    


def tgrange(*args, **kwargs): # -> tqdm_gui:
    """
    A shortcut for `tqdm.gui.tq"""
    ...

tqdm = tqdm_gui
trange = ...
