"""
This type stub file was generated by pyright.
"""

__author__ = ...
__all__ = ['TqdmCallback']
class TqdmCallback(keras.callbacks.Callback):
    """Keras callback for epoch and bat"""
    @staticmethod
    def bar2callback(bar, pop=..., delta=...): # -> (_: Unknown, logs: Unknown | None = None) -> None:
        ...
    
    def __init__(self, epochs=..., data_size=..., batch_size=..., verbose=..., tqdm_class=..., **tqdm_kwargs) -> None:
        """
        Parameters
        ----"""
        ...
    
    def on_train_begin(self, *_, **__): # -> None:
        ...
    
    def on_epoch_begin(self, epoch, *_, **__): # -> None:
        ...
    
    def on_train_end(self, *_, **__): # -> None:
        ...
    
    def display(self): # -> None:
        """Displays in the current cell in """
        ...
    


