"""
This type stub file was generated by pyright.
"""

from .std import tqdm as std_tqdm

"""
IPython/Jupyter Notebook progre"""
if True:
    IPY = ...
__author__ = ...
__all__ = ['tqdm_notebook', 'tnrange', 'tqdm', 'trange']
WARN_NOIPYW = ...
class TqdmHBox(HBox):
    """`ipywidgets.HBox` with a pretty """
    def __repr__(self, pretty=...): # -> Any:
        ...
    


class tqdm_notebook(std_tqdm):
    """
    Experimental IPython/Jupyte"""
    @staticmethod
    def status_printer(_, total=..., desc=..., ncols=...): # -> TqdmHBox:
        """
        Manage the printing of """
        ...
    
    def display(self, msg=..., pos=..., close=..., bar_style=..., check_delay=...):
        ...
    
    @property
    def colour(self): # -> None:
        ...
    
    @colour.setter
    def colour(self, bar_color): # -> None:
        ...
    
    def __init__(self, *args, **kwargs) -> None:
        """
        Supports the usual `tqd"""
        ...
    
    def __iter__(self): # -> Generator[Unknown, None, None]:
        ...
    
    def update(self, n=...):
        ...
    
    def close(self): # -> None:
        ...
    
    def clear(self, *_, **__): # -> None:
        ...
    
    def reset(self, total=...): # -> None:
        """
        Resets to 0 iterations """
        ...
    


def tnrange(*args, **kwargs): # -> tqdm_notebook:
    """
    A shortcut for `tqdm.notebo"""
    ...

tqdm = tqdm_notebook
trange = ...
