"""
This type stub file was generated by pyright.
"""

from rich.progress import ProgressColumn
from .std import tqdm as std_tqdm

"""
`rich.progress` decorator for i"""
__author__ = ...
__all__ = ['tqdm_rich', 'trrange', 'tqdm', 'trange']
class FractionColumn(ProgressColumn):
    """Renders completed/total, e.g. '0"""
    def __init__(self, unit_scale=..., unit_divisor=...) -> None:
        ...
    
    def render(self, task):
        """Calculate common unit for comple"""
        ...
    


class RateColumn(ProgressColumn):
    """Renders human readable transfer """
    def __init__(self, unit=..., unit_scale=..., unit_divisor=...) -> None:
        ...
    
    def render(self, task):
        """Show data transfer speed."""
        ...
    


class tqdm_rich(std_tqdm):
    """Experimental rich.progress GUI v"""
    def __init__(self, *args, **kwargs) -> None:
        """
        This class accepts the """
        ...
    
    def close(self): # -> None:
        ...
    
    def clear(self, *_, **__): # -> None:
        ...
    
    def display(self, *_, **__): # -> None:
        ...
    
    def reset(self, total=...): # -> None:
        """
        Resets to 0 iterations """
        ...
    


def trrange(*args, **kwargs): # -> tqdm_rich:
    """
    A shortcut for `tqdm.rich.t"""
    ...

tqdm = tqdm_rich
trange = ...
