"""
This type stub file was generated by pyright.
"""

from .std import tqdm as std_tqdm

"""
Tkinter GUI progressbar decorat"""
__author__ = ...
__all__ = ['tqdm_tk', 'ttkrange', 'tqdm', 'trange']
class tqdm_tk(std_tqdm):
    """
    Experimental Tkinter GUI ve"""
    def __init__(self, *args, **kwargs) -> None:
        """
        This class accepts the """
        ...
    
    def close(self): # -> None:
        ...
    
    def clear(self, *_, **__): # -> None:
        ...
    
    def display(self, *_, **__): # -> None:
        ...
    
    def set_description(self, desc=..., refresh=...): # -> None:
        ...
    
    def set_description_str(self, desc=..., refresh=...): # -> None:
        ...
    
    def cancel(self): # -> None:
        """
        `cancel_callback()` fol"""
        ...
    
    def reset(self, total=...): # -> None:
        """
        Resets to 0 iterations """
        ...
    


def ttkrange(*args, **kwargs): # -> tqdm_tk:
    """
    A shortcut for `tqdm.tk.tqd"""
    ...

tqdm = tqdm_tk
trange = ...
