"""
This type stub file was generated by pyright.
"""

"""
General helpers required for `t"""
CUR_OS = ...
IS_WIN = ...
IS_NIX = ...
RE_ANSI = ...
class FormatReplace:
    """
    >>> a = FormatReplace('some"""
    def __init__(self, replace=...) -> None:
        ...
    
    def __format__(self, _): # -> str:
        ...
    


class Comparable:
    """Assumes child has self._comparab"""
    def __lt__(self, other) -> bool:
        ...
    
    def __le__(self, other) -> bool:
        ...
    
    def __eq__(self, other) -> bool:
        ...
    
    def __ne__(self, other) -> bool:
        ...
    
    def __gt__(self, other) -> bool:
        ...
    
    def __ge__(self, other) -> bool:
        ...
    


class ObjectWrapper:
    def __getattr__(self, name): # -> Any:
        ...
    
    def __setattr__(self, name, value): # -> None:
        ...
    
    def wrapper_getattr(self, name): # -> Any:
        """Actual `self.getattr` rather tha"""
        ...
    
    def wrapper_setattr(self, name, value): # -> None:
        """Actual `self.setattr` rather tha"""
        ...
    
    def __init__(self, wrapped) -> None:
        """
        Thin wrapper around a g"""
        ...
    


class SimpleTextIOWrapper(ObjectWrapper):
    """
    Change only `.write()` of t"""
    def __init__(self, wrapped, encoding) -> None:
        ...
    
    def write(self, s): # -> Any:
        """
        Encode `s` and pass to """
        ...
    
    def __eq__(self, other) -> bool:
        ...
    


class DisableOnWriteError(ObjectWrapper):
    """
    Disable the given `tqdm_ins"""
    @staticmethod
    def disable_on_exception(tqdm_instance, func): # -> (*args: Unknown, **kwargs: Unknown) -> Unknown:
        """
        Quietly set `tqdm_insta"""
        ...
    
    def __init__(self, wrapped, tqdm_instance) -> None:
        ...
    
    def __eq__(self, other) -> bool:
        ...
    


class CallbackIOWrapper(ObjectWrapper):
    def __init__(self, callback, stream, method=...) -> None:
        """
        Wrap a given `file`-lik"""
        ...
    


def disp_len(data): # -> Literal[2, 1, 0]:
    """
    Returns the real on-screen """
    ...

def disp_trim(data, length):
    """
    Trim a string which may con"""
    ...

