"""
This type stub file was generated by pyright.
"""

from pptx.shapes import Subshape
from pptx.util import lazyproperty

"""Objects related to mouse click a"""
class ActionSetting(Subshape):
    """Properties specifying how a shap"""
    def __init__(self, xPr, parent, hover=...) -> None:
        ...
    
    @property
    def action(self):
        """Member of :ref:`PpActionType` en"""
        ...
    
    @lazyproperty
    def hyperlink(self): # -> Hyperlink:
        """
        A |Hyperlink| object re"""
        ...
    
    @property
    def target_slide(self): # -> None:
        """
        A reference to the slid"""
        ...
    
    @target_slide.setter
    def target_slide(self, slide): # -> None:
        ...
    


class Hyperlink(Subshape):
    """
    Represents a hyperlink acti"""
    def __init__(self, xPr, parent, hover=...) -> None:
        ...
    
    @property
    def address(self): # -> None:
        """
        Read/write. The URL of """
        ...
    
    @address.setter
    def address(self, url): # -> None:
        ...
    


