"""
This type stub file was generated by pyright.
"""

"""
Exceptions used with python-ppt"""
class PythonPptxError(Exception):
    """Generic error class."""
    ...


class PackageNotFoundError(PythonPptxError):
    """
    Raised when a package canno"""
    ...


class InvalidXmlError(PythonPptxError):
    """
    Raised when a value is enco"""
    ...


