"""
This type stub file was generated by pyright.
"""

from .util import lazyproperty

"""Objects related to images, audio"""
class Video:
    """Immutable value object represent"""
    def __init__(self, blob, mime_type, filename) -> None:
        ...
    
    @classmethod
    def from_blob(cls, blob, mime_type, filename=...): # -> Self@Video:
        """Return a new |Video| object load"""
        ...
    
    @classmethod
    def from_path_or_file_like(cls, movie_file, mime_type): # -> Self@Video:
        """Return a new |Video| object cont"""
        ...
    
    @property
    def blob(self): # -> Unknown:
        """The bytestream of the media "fil"""
        ...
    
    @property
    def content_type(self): # -> Unknown:
        """MIME-type of this media, e.g. `'"""
        ...
    
    @property
    def ext(self): # -> str* | bytes* | str:
        """Return the file extension for th"""
        ...
    
    @property
    def filename(self): # -> str* | str:
        """Return a filename.ext string app"""
        ...
    
    @lazyproperty
    def sha1(self): # -> str:
        """The SHA1 hash digest for the bin"""
        ...
    


SPEAKER_IMAGE_BYTES = ...
