"""
This type stub file was generated by pyright.
"""

from pptx.opc.package import OpcPackage
from pptx.util import lazyproperty

"""Overall .pptx package."""
class Package(OpcPackage):
    """An overall .pptx package."""
    @lazyproperty
    def core_properties(self): # -> CorePropertiesPart:
        """Instance of |CoreProperties| hol"""
        ...
    
    def get_or_add_image_part(self, image_file):
        """
        Return an |ImagePart| o"""
        ...
    
    def get_or_add_media_part(self, media):
        """Return a |MediaPart| object cont"""
        ...
    
    def next_image_partname(self, ext): # -> PackURI:
        """
        Return a |PackURI| inst"""
        ...
    
    def next_media_partname(self, ext): # -> PackURI:
        """Return |PackURI| instance for ne"""
        ...
    
    @property
    def presentation_part(self):
        """
        Reference to the |Prese"""
        ...
    


class _ImageParts:
    """Provides access to the image par"""
    def __init__(self, package) -> None:
        ...
    
    def __iter__(self): # -> Generator[Unknown, None, None]:
        """
        Generate a reference to"""
        ...
    
    def get_or_add_image_part(self, image_file): # -> ImagePart:
        """Return |ImagePart| object contai"""
        ...
    


class _MediaParts:
    """Provides access to the media par"""
    def __init__(self, package) -> None:
        ...
    
    def __iter__(self): # -> Generator[Unknown, None, None]:
        """Generate a reference to each |Me"""
        ...
    
    def get_or_add_media_part(self, media): # -> MediaPart:
        """Return a |MediaPart| object cont"""
        ...
    


