"""
This type stub file was generated by pyright.
"""

from pptx.shared import PartElementProxy
from pptx.util import lazyproperty

"""Main presentation object."""
class Presentation(PartElementProxy):
    """PresentationML (PML) presentatio"""
    @property
    def core_properties(self):
        """
        Instance of |CoreProper"""
        ...
    
    @property
    def notes_master(self):
        """
        Instance of |NotesMaste"""
        ...
    
    def save(self, file): # -> None:
        """
        Save this presentation """
        ...
    
    @property
    def slide_height(self): # -> None:
        """
        Height of slides in thi"""
        ...
    
    @slide_height.setter
    def slide_height(self, height): # -> None:
        ...
    
    @property
    def slide_layouts(self):
        """
        Sequence of |SlideLayou"""
        ...
    
    @property
    def slide_master(self):
        """
        First |SlideMaster| obj"""
        ...
    
    @lazyproperty
    def slide_masters(self): # -> SlideMasters:
        """
        Sequence of |SlideMaste"""
        ...
    
    @property
    def slide_width(self): # -> None:
        """
        Width of slides in this"""
        ...
    
    @slide_width.setter
    def slide_width(self, width): # -> None:
        ...
    
    @lazyproperty
    def slides(self): # -> Slides:
        """
        |Slides| object contain"""
        ...
    


