"""
This type stub file was generated by pyright.
"""

"""Objects shared by pptx modules."""
class ElementProxy:
    """
    Base class for lxml element"""
    def __init__(self, element) -> None:
        ...
    
    def __eq__(self, other) -> bool:
        """
        Return |True| if this p"""
        ...
    
    def __ne__(self, other) -> bool:
        ...
    
    @property
    def element(self): # -> Unknown:
        """
        The lxml element proxie"""
        ...
    


class ParentedElementProxy(ElementProxy):
    """
    Provides common services fo"""
    def __init__(self, element, parent) -> None:
        ...
    
    @property
    def parent(self): # -> Unknown:
        """
        The ancestor proxy obje"""
        ...
    
    @property
    def part(self):
        """
        The package part contai"""
        ...
    


class PartElementProxy(ElementProxy):
    """
    Provides common members for"""
    def __init__(self, element, part) -> None:
        ...
    
    @property
    def part(self): # -> Unknown:
        """
        The package part contai"""
        ...
    


