"""
This type stub file was generated by pyright.
"""

"""Objects shared by modules in the"""
class CaseInsensitiveDict(dict):
    """Mapping type like dict except it"""
    def __contains__(self, key): # -> bool:
        ...
    
    def __getitem__(self, key):
        ...
    
    def __setitem__(self, key, value): # -> None:
        ...
    


