"""
This type stub file was generated by pyright.
"""

"""
Objects used across sub-package"""
class Subshape:
    """
    Provides common services fo"""
    def __init__(self, parent) -> None:
        ...
    
    @property
    def part(self):
        """
        The package part contai"""
        ...
    


