"""
This type stub file was generated by pyright.
"""

from pptx.shapes.base import BaseShape
from pptx.util import lazyproperty

"""Connector (line) shape and relat"""
class Connector(BaseShape):
    """Connector (line) shape.

    A c"""
    def begin_connect(self, shape, cxn_pt_idx): # -> None:
        """
        **EXPERIMENTAL** - *The"""
        ...
    
    @property
    def begin_x(self): # -> Length:
        """
        Return the X-position o"""
        ...
    
    @begin_x.setter
    def begin_x(self, value): # -> None:
        ...
    
    @property
    def begin_y(self): # -> Length:
        """
        Return the Y-position o"""
        ...
    
    @begin_y.setter
    def begin_y(self, value): # -> None:
        ...
    
    def end_connect(self, shape, cxn_pt_idx): # -> None:
        """
        **EXPERIMENTAL** - *The"""
        ...
    
    @property
    def end_x(self): # -> Length:
        """
        Return the X-position o"""
        ...
    
    @end_x.setter
    def end_x(self, value): # -> None:
        ...
    
    @property
    def end_y(self): # -> Length:
        """
        Return the Y-position o"""
        ...
    
    @end_y.setter
    def end_y(self, value): # -> None:
        ...
    
    def get_or_add_ln(self):
        """Helper method required by |LineF"""
        ...
    
    @lazyproperty
    def line(self): # -> LineFormat:
        """|LineFormat| instance for this c"""
        ...
    
    @property
    def ln(self):
        """Helper method required by |LineF"""
        ...
    
    @property
    def shape_type(self):
        """Member of `MSO_SHAPE_TYPE` ident"""
        ...
    


