"""
This type stub file was generated by pyright.
"""

from pptx.shapes.base import BaseShape
from pptx.util import lazyproperty

"""GroupShape and related objects."""
class GroupShape(BaseShape):
    """A shape that acts as a container"""
    @property
    def click_action(self):
        """Unconditionally raises `TypeErro"""
        ...
    
    @property
    def has_text_frame(self): # -> Literal[False]:
        """Unconditionally |False|.

      """
        ...
    
    @lazyproperty
    def shadow(self): # -> ShadowFormat:
        """|ShadowFormat| object representi"""
        ...
    
    @property
    def shape_type(self):
        """Member of :ref:`MsoShapeType` id"""
        ...
    
    @lazyproperty
    def shapes(self): # -> GroupShapes:
        """|GroupShapes| object for this gr"""
        ...
    


