"""
This type stub file was generated by pyright.
"""

import sys
import collections
from .python3 import BytesIO, Unicode, is_integer, is_string, is_unicode, to_unicode

"""Provides Python 2/3 compatibilit"""
if sys.version_info >= (3, 0):
    ...
else:
    ...
