"""
This type stub file was generated by pyright.
"""

"""Provides Python 2 compatibility """
def is_integer(obj): # -> bool:
    """Return True if *obj* is an integ"""
    ...

def is_string(obj): # -> bool:
    """Return True if *obj* is a string"""
    ...

def is_unicode(obj): # -> bool:
    """Return True if *obj* is a unicod"""
    ...

def to_unicode(text):
    """Return *text* as a unicode strin"""
    ...

Unicode = ...
