"""
This type stub file was generated by pyright.
"""

"""Provides Python 3 compatibility """
def is_integer(obj): # -> bool:
    """
    Return True if *obj* is an """
    ...

def is_string(obj): # -> bool:
    """
    Return True if *obj* is a s"""
    ...

def is_unicode(obj): # -> bool:
    """
    Return True if *obj* is a u"""
    ...

def to_unicode(text): # -> str:
    """Return *text* as a (unicode) str"""
    ...

Unicode = str
