"""
This type stub file was generated by pyright.
"""

import os
from __future__ import absolute_import, division, print_function, unicode_literals
from lxml import etree
from .ns import NamespacePrefixedTag
from .action import CT_Hyperlink
from .chart.axis import CT_AxisUnit, CT_CatAx, CT_ChartLines, CT_Crosses, CT_DateAx, CT_LblOffset, CT_Orientation, CT_Scaling, CT_TickLblPos, CT_TickMark, CT_ValAx
from .chart.chart import CT_Chart, CT_ChartSpace, CT_ExternalData, CT_PlotArea, CT_Style
from .chart.datalabel import CT_DLbl, CT_DLblPos, CT_DLbls
from .chart.legend import CT_Legend, CT_LegendPos
from .chart.marker import CT_Marker, CT_MarkerSize, CT_MarkerStyle
from .chart.plot import CT_Area3DChart, CT_AreaChart, CT_BarChart, CT_BarDir, CT_BubbleChart, CT_BubbleScale, CT_DoughnutChart, CT_GapAmount, CT_Grouping, CT_LineChart, CT_Overlap, CT_PieChart, CT_RadarChart, CT_ScatterChart
from .chart.series import CT_AxDataSource, CT_DPt, CT_Lvl, CT_NumDataSource, CT_SeriesComposite, CT_StrVal_NumVal_Composite
from .chart.shared import CT_Boolean, CT_Boolean_Explicit, CT_Double, CT_Layout, CT_LayoutMode, CT_ManualLayout, CT_NumFmt, CT_Title, CT_Tx, CT_UnsignedInt
from .coreprops import CT_CoreProperties
from .dml.color import CT_Color, CT_HslColor, CT_Percentage, CT_PresetColor, CT_SRgbColor, CT_ScRgbColor, CT_SchemeColor, CT_SystemColor
from .dml.fill import CT_Blip, CT_BlipFillProperties, CT_GradientFillProperties, CT_GradientStop, CT_GradientStopList, CT_GroupFillProperties, CT_LinearShadeProperties, CT_NoFillProperties, CT_PatternFillProperties, CT_RelativeRect, CT_SolidColorFillProperties
from .dml.line import CT_PresetLineDashProperties
from .presentation import CT_Presentation, CT_SlideId, CT_SlideIdList, CT_SlideMasterIdList, CT_SlideMasterIdListEntry, CT_SlideSize
from .shapes.autoshape import CT_AdjPoint2D, CT_CustomGeometry2D, CT_GeomGuide, CT_GeomGuideList, CT_NonVisualDrawingShapeProps, CT_Path2D, CT_Path2DClose, CT_Path2DLineTo, CT_Path2DList, CT_Path2DMoveTo, CT_PresetGeometry2D, CT_Shape, CT_ShapeNonVisual
from .shapes.connector import CT_Connection, CT_Connector, CT_ConnectorNonVisual, CT_NonVisualConnectorProperties
from .shapes.graphfrm import CT_GraphicalObject, CT_GraphicalObjectData, CT_GraphicalObjectFrame, CT_GraphicalObjectFrameNonVisual, CT_OleObject
from .shapes.groupshape import CT_GroupShape, CT_GroupShapeNonVisual, CT_GroupShapeProperties
from .shapes.picture import CT_Picture, CT_PictureNonVisual
from .shapes.shared import CT_ApplicationNonVisualDrawingProps, CT_LineProperties, CT_NonVisualDrawingProps, CT_Placeholder, CT_Point2D, CT_PositiveSize2D, CT_ShapeProperties, CT_Transform2D
from .slide import CT_Background, CT_BackgroundProperties, CT_CommonSlideData, CT_NotesMaster, CT_NotesSlide, CT_Slide, CT_SlideLayout, CT_SlideLayoutIdList, CT_SlideLayoutIdListEntry, CT_SlideMaster, CT_SlideTiming, CT_TLMediaNodeVideo, CT_TimeNodeList
from .table import CT_Table, CT_TableCell, CT_TableCellProperties, CT_TableCol, CT_TableGrid, CT_TableProperties, CT_TableRow
from .text import CT_RegularTextRun, CT_TextBody, CT_TextBodyProperties, CT_TextCharacterProperties, CT_TextField, CT_TextFont, CT_TextLineBreak, CT_TextNormalAutofit, CT_TextParagraph, CT_TextParagraphProperties, CT_TextSpacing, CT_TextSpacingPercent, CT_TextSpacingPoint
from .theme import CT_OfficeStyleSheet

"""Initializes lxml parser, particu"""
element_class_lookup = ...
oxml_parser = ...
def parse_from_template(template_name): # -> Any:
    """
    Return an element loaded fr"""
    ...

def parse_xml(xml): # -> Any:
    """
    Return root lxml element ob"""
    ...

def register_element_cls(nsptagname, cls): # -> None:
    """
    Register *cls* to be constr"""
    ...

