"""
This type stub file was generated by pyright.
"""

from .xmlchemy import BaseOxmlElement

"""
lxml custom element classes for"""
class CT_Hyperlink(BaseOxmlElement):
    """
    Custom element class for <a"""
    rId = ...
    action = ...
    @property
    def action_fields(self): # -> dict[Unknown, Unknown]:
        """
        A dictionary containing"""
        ...
    
    @property
    def action_verb(self): # -> None:
        """
        The host portion of the"""
        ...
    


