"""
This type stub file was generated by pyright.
"""

"""
Namespace related objects.
"""
_nsmap = ...
class NamespacePrefixedTag(str):
    """
    Value object that knows the"""
    def __new__(cls, nstag, *args): # -> Self@NamespacePrefixedTag:
        ...
    
    def __init__(self, nstag) -> None:
        ...
    
    @property
    def clark_name(self): # -> str:
        ...
    
    @property
    def local_part(self):
        """
        Return the local part o"""
        ...
    
    @property
    def nsmap(self): # -> dict[Unknown, str]:
        """
        Return a dict having a """
        ...
    
    @property
    def nspfx(self):
        """
        Return the string names"""
        ...
    
    @property
    def nsuri(self): # -> str:
        """
        Return the namespace UR"""
        ...
    


def namespaces(*prefixes): # -> dict[Unknown, Unknown]:
    """
    Return a dict containing th"""
    ...

nsmap = ...
def nsdecls(*prefixes): # -> str:
    ...

def nsuri(nspfx): # -> str:
    """
    Return the namespace URI co"""
    ...

def qn(namespace_prefixed_tag): # -> str:
    """
    Return a Clark-notation qua"""
    ...

