"""
This type stub file was generated by pyright.
"""

from .xmlchemy import BaseOxmlElement

"""
Custom element classes for pres"""
class CT_Presentation(BaseOxmlElement):
    """
    ``<p:presentation>`` elemen"""
    sldMasterIdLst = ...
    sldIdLst = ...
    sldSz = ...


class CT_SlideId(BaseOxmlElement):
    """
    ``<p:sldId>`` element, dire"""
    id = ...
    rId = ...


class CT_SlideIdList(BaseOxmlElement):
    """
    ``<p:sldIdLst>`` element, d"""
    sldId = ...
    def add_sldId(self, rId):
        """
        Return a reference to a"""
        ...
    


class CT_SlideMasterIdList(BaseOxmlElement):
    """
    ``<p:sldMasterIdLst>`` elem"""
    sldMasterId = ...


class CT_SlideMasterIdListEntry(BaseOxmlElement):
    """
    ``<p:sldMasterId>`` element"""
    rId = ...


class CT_SlideSize(BaseOxmlElement):
    """
    ``<p:sldSz>`` element, dire"""
    cx = ...
    cy = ...


