"""
This type stub file was generated by pyright.
"""

from .xmlchemy import BaseOxmlElement

"""
lxml custom element classes for"""
class CT_OfficeStyleSheet(BaseOxmlElement):
    """
    ``<a:theme>`` element, root"""
    _tag_seq = ...
    @classmethod
    def new_default(cls): # -> Any:
        """
        Return a new ``<a:theme"""
        ...
    


