"""
This type stub file was generated by pyright.
"""

from .base import Enumeration, alias

"""
Enumerations that describe clic"""
@alias("PP_ACTION")
class PP_ACTION_TYPE(Enumeration):
    """
    Specifies the type of a mou"""
    __ms_name__ = ...
    __url__ = ...
    __members__ = ...


