"""
This type stub file was generated by pyright.
"""

from .base import XmlEnumeration

"""
Enumerations used for specifyin"""
class MSO_LANGUAGE_ID(XmlEnumeration):
    """
    Specifies the language iden"""
    __ms_name__ = ...
    __url__ = ...
    __members__ = ...


