"""
This type stub file was generated by pyright.
"""

from pptx.enum.base import Enumeration, XmlEnumeration, alias
from pptx.util import lazyproperty

"""Enumerations used by shapes and """
@alias("MSO_SHAPE")
class MSO_AUTO_SHAPE_TYPE(XmlEnumeration):
    """
    Specifies a type of AutoSha"""
    __ms_name__ = ...
    __url__ = ...
    __members__ = ...


@alias("MSO_CONNECTOR")
class MSO_CONNECTOR_TYPE(XmlEnumeration):
    """
    Specifies a type of connect"""
    __ms_name__ = ...
    __url__ = ...
    __members__ = ...


@alias("MSO")
class MSO_SHAPE_TYPE(Enumeration):
    """
    Specifies the type of a sha"""
    __ms_name__ = ...
    __url__ = ...
    __members__ = ...


class PP_MEDIA_TYPE(Enumeration):
    """
    Indicates the OLE media typ"""
    __ms_name__ = ...
    __url__ = ...
    __members__ = ...


@alias("PP_PLACEHOLDER")
class PP_PLACEHOLDER_TYPE(XmlEnumeration):
    """
    Specifies one of the 18 dis"""
    __ms_name__ = ...
    __url__ = ...
    __members__ = ...


class _ProgIdEnum:
    """One-off Enum-like object for pro"""
    class Member:
        """A particular progID with its att"""
        def __init__(self, name, progId, icon_filename, width, height) -> None:
            ...
        
        def __repr__(self):
            ...
        
        @property
        def height(self):
            ...
        
        @property
        def icon_filename(self):
            ...
        
        @property
        def progId(self):
            ...
        
        @property
        def width(self):
            ...
        
    
    
    def __contains__(self, item): # -> bool:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    @lazyproperty
    def DOCX(self): # -> Member:
        ...
    
    @lazyproperty
    def PPTX(self): # -> Member:
        ...
    
    @lazyproperty
    def XLSX(self): # -> Member:
        ...
    


PROG_ID = ...
