"""
This type stub file was generated by pyright.
"""

from ..shared import ElementProxy
from ..util import lazyproperty

"""
|ChartFormat| and related objec"""
class ChartFormat(ElementProxy):
    """
    The |ChartFormat| object pr"""
    @lazyproperty
    def fill(self): # -> FillFormat:
        """
        |FillFormat| instance f"""
        ...
    
    @lazyproperty
    def line(self): # -> LineFormat:
        """
        The |LineFormat| object"""
        ...
    


