"""
This type stub file was generated by pyright.
"""

"""Visual effects on a shape such a"""
class ShadowFormat:
    """Provides access to shadow effect"""
    def __init__(self, spPr) -> None:
        ...
    
    @property
    def inherit(self): # -> bool:
        """True if shape inherits shadow se"""
        ...
    
    @inherit.setter
    def inherit(self, value): # -> None:
        ...
    


