"""
This type stub file was generated by pyright.
"""

from ..util import lazyproperty

"""DrawingML objects related to lin"""
class LineFormat:
    """Provides access to line properti"""
    def __init__(self, parent) -> None:
        ...
    
    @lazyproperty
    def color(self):
        """
        The |ColorFormat| insta"""
        ...
    
    @property
    def dash_style(self): # -> None:
        """Return value indicating line sty"""
        ...
    
    @dash_style.setter
    def dash_style(self, dash_style): # -> None:
        ...
    
    @lazyproperty
    def fill(self): # -> FillFormat:
        """
        |FillFormat| instance f"""
        ...
    
    @property
    def width(self): # -> Length:
        """
        The width of the line e"""
        ...
    
    @width.setter
    def width(self, emu): # -> None:
        ...
    


