"""
This type stub file was generated by pyright.
"""

from .shared import BaseShapeElement
from ..xmlchemy import BaseOxmlElement

"""
lxml custom element classes for"""
class CT_Connection(BaseShapeElement):
    """
    A `a:stCxn` or `a:endCxn` e"""
    id = ...
    idx = ...


class CT_Connector(BaseShapeElement):
    """
    A line/connector shape ``<p"""
    _tag_seq = ...
    nvCxnSpPr = ...
    spPr = ...
    @classmethod
    def new_cxnSp(cls, id_, name, prst, x, y, cx, cy, flipH, flipV): # -> Any:
        """
        Return a new ``<p:cxnSp"""
        ...
    


class CT_ConnectorNonVisual(BaseOxmlElement):
    """
    ``<p:nvCxnSpPr>`` element, """
    cNvPr = ...
    cNvCxnSpPr = ...
    nvPr = ...


class CT_NonVisualConnectorProperties(BaseOxmlElement):
    """
    `p:cNvCxnSpPr` element, con"""
    _tag_seq = ...
    stCxn = ...
    endCxn = ...


