"""
This type stub file was generated by pyright.
"""

from pptx.oxml.shapes.shared import BaseShapeElement
from pptx.oxml.xmlchemy import BaseOxmlElement

"""lxml custom element classes for """
class CT_Picture(BaseShapeElement):
    """`p:pic` element.

    Represents"""
    nvPicPr = ...
    blipFill = ...
    spPr = ...
    @property
    def blip_rId(self): # -> None:
        """Value of `p:blipFill/a:blip/@r:e"""
        ...
    
    def crop_to_fit(self, image_size, view_size): # -> None:
        """
        Set cropping values in """
        ...
    
    def get_or_add_ln(self):
        """
        Return the <a:ln> grand"""
        ...
    
    @property
    def ln(self):
        """
        ``<a:ln>`` grand-child """
        ...
    
    @classmethod
    def new_ph_pic(cls, id_, name, desc, rId): # -> Any:
        """
        Return a new `p:pic` pl"""
        ...
    
    @classmethod
    def new_pic(cls, shape_id, name, desc, rId, x, y, cx, cy): # -> Any:
        """Return new `<p:pic>` element tre"""
        ...
    
    @classmethod
    def new_video_pic(cls, shape_id, shape_name, video_rId, media_rId, poster_frame_rId, x, y, cx, cy): # -> Any:
        """Return a new `p:pic` populated w"""
        ...
    
    @property
    def srcRect_b(self): # -> float | Any:
        """Value of `p:blipFill/a:srcRect/@"""
        ...
    
    @srcRect_b.setter
    def srcRect_b(self, value): # -> None:
        ...
    
    @property
    def srcRect_l(self): # -> float | Any:
        """Value of `p:blipFill/a:srcRect/@"""
        ...
    
    @srcRect_l.setter
    def srcRect_l(self, value): # -> None:
        ...
    
    @property
    def srcRect_r(self): # -> float | Any:
        """Value of `p:blipFill/a:srcRect/@"""
        ...
    
    @srcRect_r.setter
    def srcRect_r(self, value): # -> None:
        ...
    
    @property
    def srcRect_t(self): # -> float | Any:
        """Value of `p:blipFill/a:srcRect/@"""
        ...
    
    @srcRect_t.setter
    def srcRect_t(self, value): # -> None:
        ...
    


class CT_PictureNonVisual(BaseOxmlElement):
    """
    ``<p:nvPicPr>`` element, co"""
    cNvPr = ...
    nvPr = ...


