"""
This type stub file was generated by pyright.
"""

from pptx.compat import Sequence

"""Category-related objects.

The |"""
class Categories(Sequence):
    """
    A sequence of |category.Cat"""
    def __init__(self, xChart) -> None:
        ...
    
    def __getitem__(self, idx): # -> Category:
        ...
    
    def __iter__(self): # -> Generator[Category, None, None]:
        ...
    
    def __len__(self):
        ...
    
    @property
    def depth(self): # -> int:
        """
        Return an integer repre"""
        ...
    
    @property
    def flattened_labels(self): # -> tuple[()] | tuple[tuple[str], ...] | tuple[tuple[Unknown, ...], ...]:
        """
        Return a sequence of tu"""
        ...
    
    @property
    def levels(self): # -> list[CategoryLevel]:
        """
        Return a sequence of |C"""
        ...
    


class Category(str):
    """
    An extension of `str` that """
    def __new__(cls, pt, *args): # -> Self@Category:
        ...
    
    def __init__(self, pt, idx=...) -> None:
        """
        *idx* is a required att"""
        ...
    
    @property
    def idx(self): # -> Unknown:
        """
        Return an integer repre"""
        ...
    
    @property
    def label(self): # -> str:
        """
        Return the label of thi"""
        ...
    


class CategoryLevel(Sequence):
    """
    A sequence of |category.Cat"""
    def __init__(self, lvl) -> None:
        ...
    
    def __getitem__(self, offset): # -> Category:
        ...
    
    def __len__(self): # -> int:
        ...
    


