"""
This type stub file was generated by pyright.
"""

from ..util import lazyproperty

"""
Legend of a chart.
"""
class Legend:
    """
    Represents the legend in a """
    def __init__(self, legend_elm) -> None:
        ...
    
    @lazyproperty
    def font(self): # -> Font:
        """
        The |Font| object that """
        ...
    
    @property
    def horz_offset(self):
        """
        Adjustment of the x pos"""
        ...
    
    @horz_offset.setter
    def horz_offset(self, value): # -> None:
        ...
    
    @property
    def include_in_layout(self): # -> Literal[True]:
        """|True| if legend should be locat"""
        ...
    
    @include_in_layout.setter
    def include_in_layout(self, value): # -> None:
        ...
    
    @property
    def position(self):
        """
        Read/write :ref:`XlLege"""
        ...
    
    @position.setter
    def position(self, position): # -> None:
        ...
    


