"""
This type stub file was generated by pyright.
"""

from ..shared import ElementProxy
from ..util import lazyproperty

"""
Marker-related objects. Only th"""
class Marker(ElementProxy):
    """
    Represents a data point mar"""
    @lazyproperty
    def format(self): # -> ChartFormat:
        """
        The |ChartFormat| insta"""
        ...
    
    @property
    def size(self): # -> None:
        """
        An integer between 2 an"""
        ...
    
    @size.setter
    def size(self, value): # -> None:
        ...
    
    @property
    def style(self): # -> None:
        """
        A member of the :ref:`X"""
        ...
    
    @style.setter
    def style(self, value): # -> None:
        ...
    


