"""
This type stub file was generated by pyright.
"""

from pptx.compat import Sequence
from pptx.util import lazyproperty

"""Data point-related objects."""
class _BasePoints(Sequence):
    """
    Sequence providing access t"""
    def __init__(self, ser) -> None:
        ...
    
    def __getitem__(self, idx): # -> Point:
        ...
    


class BubblePoints(_BasePoints):
    """
    Sequence providing access t"""
    def __len__(self):
        ...
    


class CategoryPoints(_BasePoints):
    """
    Sequence providing access t"""
    def __len__(self):
        ...
    


class Point:
    """
    Provides access to the prop"""
    def __init__(self, ser, idx) -> None:
        ...
    
    @lazyproperty
    def data_label(self): # -> DataLabel:
        """
        The |DataLabel| object """
        ...
    
    @lazyproperty
    def format(self): # -> ChartFormat:
        """
        The |ChartFormat| objec"""
        ...
    
    @lazyproperty
    def marker(self): # -> Marker:
        """
        The |Marker| instance f"""
        ...
    


class XyPoints(_BasePoints):
    """
    Sequence providing access t"""
    def __len__(self):
        ...
    


