"""
This type stub file was generated by pyright.
"""

"""
Composers for default chart XML"""
def ChartXmlWriter(chart_type, chart_data): # -> _AreaChartXmlWriter | _BarChartXmlWriter | _BubbleChartXmlWriter | _DoughnutChartXmlWriter | _LineChartXmlWriter | _PieChartXmlWriter | _RadarChartXmlWriter | _XyChartXmlWriter:
    """
    Factory function returning """
    ...

def SeriesXmlRewriterFactory(chart_type, chart_data): # -> _BubbleSeriesXmlRewriter | _XySeriesXmlRewriter | _CategorySeriesXmlRewriter:
    """
    Return a |_BaseSeriesXmlRew"""
    ...

class _BaseChartXmlWriter:
    """
    Generates XML text (unicode"""
    def __init__(self, chart_type, series_seq) -> None:
        ...
    
    @property
    def xml(self):
        """
        The full XML stream for"""
        ...
    


class _BaseSeriesXmlWriter:
    """
    Provides shared members for"""
    def __init__(self, series, date_1904=...) -> None:
        ...
    
    @property
    def name(self): # -> str:
        """
        The XML-escaped name fo"""
        ...
    
    def numRef_xml(self, wksht_ref, number_format, values): # -> str:
        """
        Return the ``<c:numRef>"""
        ...
    
    def pt_xml(self, values): # -> str:
        """
        Return the ``<c:ptCount"""
        ...
    
    @property
    def tx(self): # -> Any:
        """
        Return a ``<c:tx>`` oxm"""
        ...
    
    @property
    def tx_xml(self): # -> str:
        """
        Return the ``<c:tx>`` ("""
        ...
    


class _BaseSeriesXmlRewriter:
    """
    Base class for series XML r"""
    def __init__(self, chart_data) -> None:
        ...
    
    def replace_series_data(self, chartSpace): # -> None:
        """
        Rewrite the series data"""
        ...
    


class _AreaChartXmlWriter(_BaseChartXmlWriter):
    """
    Provides specialized method"""
    @property
    def xml(self): # -> str:
        ...
    


class _BarChartXmlWriter(_BaseChartXmlWriter):
    """
    Provides specialized method"""
    @property
    def xml(self): # -> str:
        ...
    


class _DoughnutChartXmlWriter(_BaseChartXmlWriter):
    """
    Provides specialized method"""
    @property
    def xml(self): # -> str:
        ...
    


class _LineChartXmlWriter(_BaseChartXmlWriter):
    """
    Provides specialized method"""
    @property
    def xml(self): # -> str:
        ...
    


class _PieChartXmlWriter(_BaseChartXmlWriter):
    """
    Provides specialized method"""
    @property
    def xml(self): # -> str:
        ...
    


class _RadarChartXmlWriter(_BaseChartXmlWriter):
    """
    Generates XML for the ``<c:"""
    @property
    def xml(self): # -> str:
        ...
    


class _XyChartXmlWriter(_BaseChartXmlWriter):
    """
    Generates XML for the ``<c:"""
    @property
    def xml(self): # -> str:
        ...
    


class _BubbleChartXmlWriter(_XyChartXmlWriter):
    """
    Provides specialized method"""
    @property
    def xml(self): # -> str:
        ...
    


class _CategorySeriesXmlWriter(_BaseSeriesXmlWriter):
    """
    Generates XML snippets part"""
    @property
    def cat(self): # -> Any:
        """
        Return the ``<c:cat>`` """
        ...
    
    @property
    def cat_xml(self): # -> str:
        """
        The unicode XML snippet"""
        ...
    
    @property
    def val(self): # -> Any:
        """
        The ``<c:val>`` XML for"""
        ...
    
    @property
    def val_xml(self): # -> str:
        """
        Return the unicode XML """
        ...
    


class _XySeriesXmlWriter(_BaseSeriesXmlWriter):
    """
    Generates XML snippets part"""
    @property
    def xVal(self): # -> Any:
        """
        Return the ``<c:xVal>``"""
        ...
    
    @property
    def xVal_xml(self): # -> str:
        """
        Return the ``<c:xVal>``"""
        ...
    
    @property
    def yVal(self): # -> Any:
        """
        Return the ``<c:yVal>``"""
        ...
    
    @property
    def yVal_xml(self): # -> str:
        """
        Return the ``<c:yVal>``"""
        ...
    


class _BubbleSeriesXmlWriter(_XySeriesXmlWriter):
    """
    Generates XML snippets part"""
    @property
    def bubbleSize(self): # -> Any:
        """
        Return the ``<c:bubbleS"""
        ...
    
    @property
    def bubbleSize_xml(self): # -> str:
        """
        Return the ``<c:bubbleS"""
        ...
    


class _BubbleSeriesXmlRewriter(_BaseSeriesXmlRewriter):
    """
    A series rewriter suitable """
    ...


class _CategorySeriesXmlRewriter(_BaseSeriesXmlRewriter):
    """
    A series rewriter suitable """
    ...


class _XySeriesXmlRewriter(_BaseSeriesXmlRewriter):
    """
    A series rewriter suitable """
    ...


