"""
This type stub file was generated by pyright.
"""

from ..xmlchemy import BaseOxmlElement

"""
lxml custom element classes for"""
class CT_Legend(BaseOxmlElement):
    """
    ``<c:legend>`` custom eleme"""
    _tag_seq = ...
    legendPos = ...
    layout = ...
    overlay = ...
    txPr = ...
    @property
    def defRPr(self):
        """
        `./c:txPr/a:p/a:pPr/a:d"""
        ...
    
    @property
    def horz_offset(self): # -> float:
        """
        The float value in ./c:"""
        ...
    
    @horz_offset.setter
    def horz_offset(self, offset): # -> None:
        """
        Set the value of ./c:la"""
        ...
    


class CT_LegendPos(BaseOxmlElement):
    """
    ``<c:legendPos>`` element s"""
    val = ...


