"""
This type stub file was generated by pyright.
"""

from ..xmlchemy import BaseOxmlElement

"""
Series-related oxml objects.
"""
class CT_Marker(BaseOxmlElement):
    """
    `c:marker` custom element c"""
    _tag_seq = ...
    symbol = ...
    size = ...
    spPr = ...
    @property
    def size_val(self): # -> None:
        """
        Return the value of `./"""
        ...
    
    @property
    def symbol_val(self): # -> None:
        """
        Return the value of `./"""
        ...
    


class CT_MarkerSize(BaseOxmlElement):
    """
    `c:size` custom element cla"""
    val = ...


class CT_MarkerStyle(BaseOxmlElement):
    """
    `c:symbol` custom element c"""
    val = ...


