"""
This type stub file was generated by pyright.
"""

from ..xmlchemy import BaseOxmlElement

"""
Plot-related oxml objects.
"""
class BaseChartElement(BaseOxmlElement):
    """
    Base class for barChart, li"""
    @property
    def cat(self): # -> None:
        """
        Return the `c:cat` elem"""
        ...
    
    @property
    def cat_pt_count(self): # -> Literal[0]:
        """
        Return the value of the"""
        ...
    
    @property
    def cat_pts(self): # -> list[Unknown | None]:
        """
        Return a sequence repre"""
        ...
    
    @property
    def grouping_val(self): # -> Literal['standard']:
        """
        Return the value of the"""
        ...
    
    def iter_sers(self): # -> Generator[Unknown, None, None]:
        """
        Generate each ``<c:ser>"""
        ...
    
    @property
    def sers(self): # -> tuple[Unknown, ...]:
        """
        Sequence of ``<c:ser>``"""
        ...
    


class CT_Area3DChart(BaseChartElement):
    """
    ``<c:area3DChart>`` element"""
    grouping = ...


class CT_AreaChart(BaseChartElement):
    """
    ``<c:areaChart>`` element.
"""
    _tag_seq = ...
    grouping = ...
    varyColors = ...
    ser = ...
    dLbls = ...


class CT_BarChart(BaseChartElement):
    """
    ``<c:barChart>`` element.
 """
    _tag_seq = ...
    barDir = ...
    grouping = ...
    varyColors = ...
    ser = ...
    dLbls = ...
    gapWidth = ...
    overlap = ...
    @property
    def grouping_val(self): # -> Literal['clustered']:
        """
        Return the value of the"""
        ...
    


class CT_BarDir(BaseOxmlElement):
    """
    ``<c:barDir>`` child of a b"""
    val = ...


class CT_BubbleChart(BaseChartElement):
    """
    ``<c:bubbleChart>`` custom """
    _tag_seq = ...
    ser = ...
    dLbls = ...
    bubble3D = ...
    bubbleScale = ...


class CT_BubbleScale(BaseChartElement):
    """
    ``<c:bubbleScale>`` custom """
    val = ...


class CT_DoughnutChart(BaseChartElement):
    """
    ``<c:doughnutChart>`` eleme"""
    _tag_seq = ...
    varyColors = ...
    ser = ...
    dLbls = ...


class CT_GapAmount(BaseOxmlElement):
    """
    ``<c:gapWidth>`` child of `"""
    val = ...


class CT_Grouping(BaseOxmlElement):
    """
    ``<c:grouping>`` child of a"""
    val = ...


class CT_LineChart(BaseChartElement):
    """
    ``<c:lineChart>`` custom el"""
    _tag_seq = ...
    grouping = ...
    varyColors = ...
    ser = ...
    dLbls = ...


class CT_Overlap(BaseOxmlElement):
    """
    ``<c:overlap>`` element spe"""
    val = ...


class CT_PieChart(BaseChartElement):
    """
    ``<c:pieChart>`` custom ele"""
    _tag_seq = ...
    varyColors = ...
    ser = ...
    dLbls = ...


class CT_RadarChart(BaseChartElement):
    """
    ``<c:radarChart>`` custom e"""
    _tag_seq = ...
    varyColors = ...
    ser = ...
    dLbls = ...


class CT_ScatterChart(BaseChartElement):
    """
    ``<c:scatterChart>`` custom"""
    _tag_seq = ...
    varyColors = ...
    ser = ...


