"""
This type stub file was generated by pyright.
"""

from pptx.oxml.xmlchemy import BaseOxmlElement

"""Shared oxml objects for charts."""
class CT_Boolean(BaseOxmlElement):
    """
    Common complex type used fo"""
    val = ...


class CT_Boolean_Explicit(BaseOxmlElement):
    """Always spells out the `val` attr"""
    _val = ...
    @property
    def val(self): # -> OptionalAttribute:
        ...
    
    @val.setter
    def val(self, value): # -> None:
        ...
    


class CT_Double(BaseOxmlElement):
    """
    Used for floating point val"""
    val = ...


class CT_Layout(BaseOxmlElement):
    """
    ``<c:layout>`` custom eleme"""
    manualLayout = ...
    @property
    def horz_offset(self): # -> float:
        """
        The float value in ./c:"""
        ...
    
    @horz_offset.setter
    def horz_offset(self, offset): # -> None:
        """
        Set the value of ./c:ma"""
        ...
    


class CT_LayoutMode(BaseOxmlElement):
    """
    Used for ``<c:xMode>``, ``<"""
    val = ...


class CT_ManualLayout(BaseOxmlElement):
    """
    ``<c:manualLayout>`` custom"""
    _tag_seq = ...
    xMode = ...
    x = ...
    @property
    def horz_offset(self): # -> float:
        """
        The float value in ./c:"""
        ...
    
    @horz_offset.setter
    def horz_offset(self, offset): # -> None:
        """
        Set the value of ./c:x@"""
        ...
    


class CT_NumFmt(BaseOxmlElement):
    """
    ``<c:numFmt>`` element spec"""
    formatCode = ...
    sourceLinked = ...


class CT_Title(BaseOxmlElement):
    """`c:title` custom element class."""
    _tag_seq = ...
    tx = ...
    spPr = ...
    def get_or_add_tx_rich(self):
        """Return `c:tx/c:rich`, newly crea"""
        ...
    
    @property
    def tx_rich(self): # -> None:
        """Return `c:tx/c:rich` or |None| i"""
        ...
    
    @staticmethod
    def new_title(): # -> Any:
        """Return "loose" `c:title` element"""
        ...
    


class CT_Tx(BaseOxmlElement):
    """
    ``<c:tx>`` element containi"""
    strRef = ...
    rich = ...


class CT_UnsignedInt(BaseOxmlElement):
    """
    ``<c:idx>`` element and oth"""
    val = ...


